### ISSUE TITLE
Game doesn't start on Ubuntu 16.04

### ISSUE THREAD

**Issue by benaiu** [libavg/mtc-geneatd#9]
$ geneatd 
Traceback (most recent call last):
  File "/usr/games/geneatd", line 29, in <module>
    import geneatd
  File "/usr/share/games/geneatd/__init__.py", line 3, in <module>
    from war import GeneaTD
  File "/usr/share/games/geneatd/war.py", line 80, in <module>
    class GeneaTD(gameapp.GameApp):   
NameError: name 'gameapp' is not defined

-----------game version
1.0+svn6511+dfsg-0ubuntu2
from ubuntu 16.04 repo (just installed)

**Comment by MichaelMauderer** [comment]
This sounds like a version incompatibility issue.
Which version of libavg and Python is this bundled with?

**Comment by benaiu** [comment]
I don't really know how to answer that, but i can give you some similar information from the package manager:
```
apt show python2.7
Package: python2.7
Version: 2.7.12-1ubuntu0~16.04.4
Priority: optional
Section: python
Origin: Ubuntu
Maintainer: Ubuntu Core Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Matthias Klose <doko@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 358 kB
Depends: python2.7-minimal (= 2.7.12-1ubuntu0~16.04.4), libpython2.7-stdlib (= 2.7.12-1ubuntu0~16.04.4), mime-support
Suggests: python2.7-doc, binutils
Conflicts: python-profiler (<= 2.7.1-2)
Breaks: python-virtualenv (<< 1.7.1.2-2~), vim-athena (<< 2:7.3.547-4), vim-gnome (<< 2:7.3.547-4), vim-gtk (<< 2:7.3.547-4), vim-nox (<< 2:7.3.547-4)
Replaces: python-profiler (<= 2.7.1-2), python2.7-minimal (<< 2.7.3-7~)
Task: ubuntu-desktop, ubuntu-usb, dns-server, samba-server, kubuntu-desktop, kubuntu-full, edubuntu-desktop, edubuntu-usb, xubuntu-desktop, mythbuntu-frontend, mythbuntu-frontend, mythbuntu-desktop, mythbuntu-backend-slave, mythbuntu-backend-slave, mythbuntu-backend-master, mythbuntu-backend-master, lubuntu-core, ubuntustudio-desktop-core, ubuntustudio-desktop, ubuntustudio-fonts, ubuntu-gnome-desktop, ubuntu-sdk-libs-dev, ubuntukylin-desktop, ubuntu-mate-core, ubuntu-mate-desktop, ubuntu-mate-cloudtop
Supported: 5y
Download-Size: 224 kB
APT-Manual-Installed: yes
```

```
$ apt show python-libavg 
Package: python-libavg
Version: 1.8.1-2
Priority: optional
Section: universe/python
Source: libavg
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Dimitri John Ledkov <xnox@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 13,7 MB
Provides: python2.7-libavg
Depends: python (>= 2.7), python (<< 2.8), libavcodec-ffmpeg56 (>= 7:2.4) | libavcodec-ffmpeg-extra56 (>= 7:2.4), libavformat-ffmpeg56 (>= 7:2.4), libavresample-ffmpeg2 (>= 7:2.4), libavutil-ffmpeg54 (>= 7:2.4), libboost-python1.58.0, libboost-system1.58.0, libboost-thread1.58.0, libc6 (>= 2.17), libcairo2 (>= 1.2.4), libdc1394-22, libfontconfig1 (>= 2.9.0), libgcc1 (>= 1:4.1.1), libgdk-pixbuf2.0-0 (>= 2.22.0), libgl1-mesa-glx | libgl1, libglib2.0-0 (>= 2.12.0), libglu1-mesa | libglu1, libmtdev1 (>= 1.0.8), libpango-1.0-0 (>= 1.22.0), libpangoft2-1.0-0 (>= 1.14.0), libpython2.7 (>= 2.7), librsvg2-2 (>= 2.26.0), libsdl1.2debian (>= 1.2.11), libstdc++6 (>= 5.2), libswscale-ffmpeg3 (>= 7:2.4), libvdpau1 (>= 0.2), libx11-6 (>= 2:1.2.99.901), libxi6 (>= 2:1.2.99.4), libxml2 (>= 2.7.4), libxxf86vm1
```

```
apt show geneatd
Package: geneatd
Version: 1.0+svn6511+dfsg-0ubuntu2
Priority: optional
Section: universe/games
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: OXullo Intersecans <x@brainrapers.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 11,3 MB
Depends: python (>= 2.7.1-0ubuntu2), python-libavg (>= 1.7.0), ttf-dejavu-extra
Download-Size: 10,8 MB
APT-Manual-Installed: yes
```

**Comment by MichaelMauderer** [comment]
Yeah, it seems that Ubuntu ships with an out of date version of GeneaTD.
Easiest way to fix that, would be to just run it from source. The current repo version should work with the current libavg version.

**Comment by MichaelMauderer** [comment]
I don't think there is a big chance of the package getting updated. Maybe one of the libavg maintainers @oxullo ?) might now. But in the meantime I'm lcosing this.
